--- #YAML:1.0
name: Syntax-Highlight-HTML
version: 0.02
author: |-
  Sébastien Aperghis-Tramoni <sebastien@aperghis.net>
abstract: Highlight HTML syntax
license: perl
requires:
  HTML::Parser: 3
provides:
  Syntax::Highlight::HTML:
    file: lib/Syntax/Highlight/HTML.pm
    version: 0.02
generated_by: Module::Build version 0.25
